on:
  push:
    branches:
      - master

name: master
jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'VERSION-SKIP-CI')"
    strategy:
      matrix:
        python-version: [ 3.6 ]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: build
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
          make install
          make sdist
      - name: topypi
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.pypi_login }}
          password: ${{ secrets.pypi_passwd }}
          skip_existing: true
          verbose: true
      - name: todocker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.docker_login }}
          password: ${{ secrets.docker_passwd }}
          repository: advestisrepositories/ripe
          tag_with_ref: true